name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release-create:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
